apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-token-dashboard
  namespace: ai-token-dashboard
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
    - host: myai.carher.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-token-dashboard
                port: {name: http}
